/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LizenzenRouteImport } from './routes/lizenzen'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProjektSlugRouteImport } from './routes/projekt/$slug'
import { Route as OgSlugDotpngRouteImport } from './routes/og/$slug[.]png'
import { Route as AdminStatsRouteImport } from './routes/admin/stats'
import { Route as AdminBvvRouteImport } from './routes/admin/bvv'

const LizenzenRoute = LizenzenRouteImport.update({
  id: '/lizenzen',
  path: '/lizenzen',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ProjektSlugRoute = ProjektSlugRouteImport.update({
  id: '/projekt/$slug',
  path: '/projekt/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OgSlugDotpngRoute = OgSlugDotpngRouteImport.update({
  id: '/og/$slug.png',
  path: '/og/$slug.png',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatsRoute = AdminStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBvvRoute = AdminBvvRouteImport.update({
  id: '/bvv',
  path: '/bvv',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/lizenzen': typeof LizenzenRoute
  '/admin/bvv': typeof AdminBvvRoute
  '/admin/stats': typeof AdminStatsRoute
  '/og/$slug.png': typeof OgSlugDotpngRoute
  '/projekt/$slug': typeof ProjektSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/lizenzen': typeof LizenzenRoute
  '/admin/bvv': typeof AdminBvvRoute
  '/admin/stats': typeof AdminStatsRoute
  '/og/$slug.png': typeof OgSlugDotpngRoute
  '/projekt/$slug': typeof ProjektSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/lizenzen': typeof LizenzenRoute
  '/admin/bvv': typeof AdminBvvRoute
  '/admin/stats': typeof AdminStatsRoute
  '/og/$slug.png': typeof OgSlugDotpngRoute
  '/projekt/$slug': typeof ProjektSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/datenschutz'
    | '/impressum'
    | '/lizenzen'
    | '/admin/bvv'
    | '/admin/stats'
    | '/og/$slug.png'
    | '/projekt/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/lizenzen'
    | '/admin/bvv'
    | '/admin/stats'
    | '/og/$slug.png'
    | '/projekt/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/datenschutz'
    | '/impressum'
    | '/lizenzen'
    | '/admin/bvv'
    | '/admin/stats'
    | '/og/$slug.png'
    | '/projekt/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  LizenzenRoute: typeof LizenzenRoute
  OgSlugDotpngRoute: typeof OgSlugDotpngRoute
  ProjektSlugRoute: typeof ProjektSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lizenzen': {
      id: '/lizenzen'
      path: '/lizenzen'
      fullPath: '/lizenzen'
      preLoaderRoute: typeof LizenzenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/projekt/$slug': {
      id: '/projekt/$slug'
      path: '/projekt/$slug'
      fullPath: '/projekt/$slug'
      preLoaderRoute: typeof ProjektSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/$slug.png': {
      id: '/og/$slug.png'
      path: '/og/$slug.png'
      fullPath: '/og/$slug.png'
      preLoaderRoute: typeof OgSlugDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stats': {
      id: '/admin/stats'
      path: '/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AdminStatsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/bvv': {
      id: '/admin/bvv'
      path: '/bvv'
      fullPath: '/admin/bvv'
      preLoaderRoute: typeof AdminBvvRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminBvvRoute: typeof AdminBvvRoute
  AdminStatsRoute: typeof AdminStatsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBvvRoute: AdminBvvRoute,
  AdminStatsRoute: AdminStatsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  LizenzenRoute: LizenzenRoute,
  OgSlugDotpngRoute: OgSlugDotpngRoute,
  ProjektSlugRoute: ProjektSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
